-- 더미 데이터 생성 SQL
-- 실행 전 기존 데이터 정리 (필요시 주석 해제)
-- TRUNCATE TABLE post RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE board RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE board_group RESTART IDENTITY CASCADE;

-- BoardGroup 더미 데이터 (50개)
INSERT INTO board_group (title, description) VALUES
('General Discussion', 'General discussion topics for all users'),
('Technology News', 'Latest technology trends and news'),
('Programming Tips', 'Programming best practices and tips'),
('Web Development', 'Frontend and backend web development'),
('Mobile Development', 'iOS and Android development discussions'),
('DevOps & Infrastructure', 'DevOps tools and infrastructure management'),
('Data Science', 'Data analysis, machine learning, and AI'),
('Security', 'Cybersecurity and information security'),
('Career Advice', 'Professional development and career guidance'),
('Project Showcase', 'Show off your latest projects'),
('Open Source', 'Open source projects and contributions'),
('Code Review', 'Code review requests and feedback'),
('Algorithms & DS', 'Data structures and algorithms discussion'),
('Database Design', 'Database architecture and optimization'),
('UI/UX Design', 'User interface and experience design'),
('Testing & QA', 'Testing strategies and quality assurance'),
('Architecture', 'Software architecture and system design'),
('Performance', 'Performance optimization and monitoring'),
('Documentation', 'Documentation best practices'),
('Troubleshooting', 'Bug reports and problem solving'),
('News & Updates', 'Industry news and platform updates'),
('Tutorials', 'Step-by-step learning materials'),
('Q&A', 'Questions and answers'),
('Book Reviews', 'Technical book discussions and reviews'),
('Conference Talks', 'Conference presentations and talks'),
('Tools & Resources', 'Useful development tools and resources'),
('Freelancing', 'Freelance work and client management'),
('Startup Life', 'Startup experiences and advice'),
('Remote Work', 'Remote working tips and experiences'),
('Team Management', 'Managing development teams'),
('Product Management', 'Product development and management'),
('Marketing Tech', 'Marketing technology and strategies'),
('E-commerce', 'E-commerce development and platforms'),
('Gaming Dev', 'Game development discussions'),
('IoT & Embedded', 'Internet of Things and embedded systems'),
('Blockchain', 'Blockchain technology and cryptocurrency'),
('API Development', 'REST, GraphQL, and API design'),
('Cloud Computing', 'AWS, GCP, Azure cloud services'),
('Containerization', 'Docker, Kubernetes container technology'),
('Monitoring', 'Application monitoring and observability'),
('Networking', 'Network programming and protocols'),
('Frontend Frameworks', 'React, Vue, Angular discussions'),
('Backend Frameworks', 'Node.js, Django, Spring discussions'),
('Machine Learning', 'ML algorithms and implementations'),
('Data Engineering', 'Data pipelines and ETL processes'),
('Analytics', 'Data analytics and business intelligence'),
('Research Papers', 'Academic papers and research discussions'),
('Internships', 'Internship experiences and opportunities'),
('Bootcamps', 'Coding bootcamp experiences'),
('Community Events', 'Meetups, hackathons, and events');

-- Board 더미 데이터 (50개, 대부분 BoardGroup과 연결)
INSERT INTO board (title, slug, description, board_group_id, created_at) VALUES
('Daily Tech Talk', 'daily-tech-talk', 'Daily discussions about technology trends', 2, NOW() - INTERVAL '30 days'),
('JavaScript Tips', 'javascript-tips', 'JavaScript programming tips and tricks', 3, NOW() - INTERVAL '29 days'),
('React Best Practices', 'react-best-practices', 'Best practices for React development', 4, NOW() - INTERVAL '28 days'),
('Flutter Development', 'flutter-development', 'Cross-platform mobile development with Flutter', 5, NOW() - INTERVAL '27 days'),
('Docker Containers', 'docker-containers', 'Containerization with Docker', 6, NOW() - INTERVAL '26 days'),
('Machine Learning Algorithms', 'ml-algorithms', 'Discussion about ML algorithms', 7, NOW() - INTERVAL '25 days'),
('InfoSec News', 'infosec-news', 'Latest cybersecurity news and threats', 8, NOW() - INTERVAL '24 days'),
('Junior Developer Guide', 'junior-dev-guide', 'Guidance for junior developers', 9, NOW() - INTERVAL '23 days'),
('Amazing Projects', 'amazing-projects', 'Showcase your incredible projects', 10, NOW() - INTERVAL '22 days'),
('OSS Contributions', 'oss-contributions', 'Open source contribution discussions', 11, NOW() - INTERVAL '21 days'),
('Code Review Board', 'code-review-board', 'Get your code reviewed by peers', 12, NOW() - INTERVAL '20 days'),
('Algorithm Challenges', 'algorithm-challenges', 'Challenging algorithmic problems', 13, NOW() - INTERVAL '19 days'),
('PostgreSQL Optimization', 'postgresql-optimization', 'Database optimization techniques', 14, NOW() - INTERVAL '18 days'),
('Design Systems', 'design-systems', 'Building consistent design systems', 15, NOW() - INTERVAL '17 days'),
('TDD Practices', 'tdd-practices', 'Test-driven development practices', 16, NOW() - INTERVAL '16 days'),
('Microservices Architecture', 'microservices-arch', 'Microservices design patterns', 17, NOW() - INTERVAL '15 days'),
('Performance Tuning', 'performance-tuning', 'Application performance optimization', 18, NOW() - INTERVAL '14 days'),
('API Documentation', 'api-documentation', 'Writing great API documentation', 19, NOW() - INTERVAL '13 days'),
('Debugging Hell', 'debugging-hell', 'Troubleshooting difficult bugs', 20, NOW() - INTERVAL '12 days'),
('Tech Industry News', 'tech-industry-news', 'Latest tech industry updates', 21, NOW() - INTERVAL '11 days'),
('Learning Resources', 'learning-resources', 'Great tutorials and courses', 22, NOW() - INTERVAL '10 days'),
('Help Desk', 'help-desk', 'Get help with your coding problems', 23, NOW() - INTERVAL '9 days'),
('Programming Books', 'programming-books', 'Recommended programming books', 24, NOW() - INTERVAL '8 days'),
('Conference Highlights', 'conference-highlights', 'Best talks from tech conferences', 25, NOW() - INTERVAL '7 days'),
('Dev Tools', 'dev-tools', 'Useful development tools and utilities', 26, NOW() - INTERVAL '6 days'),
('Freelance Projects', 'freelance-projects', 'Freelancing tips and project management', 27, NOW() - INTERVAL '5 days'),
('Startup Stories', 'startup-stories', 'Startup journey and experiences', 28, NOW() - INTERVAL '4 days'),
('Remote Working', 'remote-working', 'Remote work productivity tips', 29, NOW() - INTERVAL '3 days'),
('Agile Teams', 'agile-teams', 'Agile development and team management', 30, NOW() - INTERVAL '2 days'),
('Product Strategy', 'product-strategy', 'Product development strategies', 31, NOW() - INTERVAL '1 day'),
('Marketing for Devs', 'marketing-for-devs', 'Marketing strategies for developers', 32, NOW()),
('E-commerce Solutions', 'ecommerce-solutions', 'E-commerce platform development', 33, NOW() - INTERVAL '1 hour'),
('Indie Game Dev', 'indie-game-dev', 'Independent game development', 34, NOW() - INTERVAL '2 hours'),
('IoT Projects', 'iot-projects', 'Internet of Things project showcase', 35, NOW() - INTERVAL '3 hours'),
('Crypto Development', 'crypto-development', 'Blockchain and cryptocurrency development', 36, NOW() - INTERVAL '4 hours'),
('GraphQL APIs', 'graphql-apis', 'GraphQL API development and best practices', 37, NOW() - INTERVAL '5 hours'),
('AWS Solutions', 'aws-solutions', 'Amazon Web Services solutions and tips', 38, NOW() - INTERVAL '6 hours'),
('Kubernetes Deployment', 'k8s-deployment', 'Kubernetes deployment strategies', 39, NOW() - INTERVAL '7 hours'),
('App Monitoring', 'app-monitoring', 'Application monitoring and alerting', 40, NOW() - INTERVAL '8 hours'),
('Network Programming', 'network-programming', 'Low-level network programming', 41, NOW() - INTERVAL '9 hours'),
('Vue.js Community', 'vuejs-community', 'Vue.js framework discussions', 42, NOW() - INTERVAL '10 hours'),
('Node.js Backend', 'nodejs-backend', 'Node.js backend development', 43, NOW() - INTERVAL '11 hours'),
('Deep Learning', 'deep-learning', 'Deep learning models and techniques', 44, NOW() - INTERVAL '12 hours'),
('Data Pipelines', 'data-pipelines', 'Building robust data pipelines', 45, NOW() - INTERVAL '13 hours'),
('Business Intelligence', 'business-intelligence', 'BI tools and analytics', 46, NOW() - INTERVAL '14 hours'),
('Research Papers', 'research-papers', 'Academic research in computer science', 47, NOW() - INTERVAL '15 hours'),
('Internship Experience', 'internship-experience', 'Share your internship stories', 48, NOW() - INTERVAL '16 hours'),
('Bootcamp Journey', 'bootcamp-journey', 'Coding bootcamp experiences', 49, NOW() - INTERVAL '17 hours'),
('Random Thoughts', 'random-thoughts', 'Miscellaneous development thoughts', NULL, NOW() - INTERVAL '18 hours'),
('Announcements', 'announcements', 'Important platform announcements', NULL, NOW() - INTERVAL '19 hours'),
('General Chat', 'general-chat', 'General conversation space', 1, NOW() - INTERVAL '20 hours');

-- Post 더미 데이터 (각 Board에 1개 이상, 총 50개)
INSERT INTO post (title, content, board_id, read_time, created_at) VALUES
('The Future of JavaScript in 2024', 'JavaScript continues to evolve rapidly with new features like top-level await, private fields, and improved performance. Here''s what we can expect in 2024...', 1, 5, NOW() - INTERVAL '1 day'),
('10 Essential JavaScript Array Methods', 'Master these array methods to write cleaner, more efficient code: map(), filter(), reduce(), find(), and more. Each method serves a specific purpose...', 2, 7, NOW() - INTERVAL '2 days'),
('React 18 Concurrent Features Deep Dive', 'React 18 introduced concurrent features that revolutionise how we think about rendering. Let''s explore Suspense, concurrent rendering, and automatic batching...', 3, 12, NOW() - INTERVAL '3 days'),
('Building Your First Flutter App', 'Flutter makes cross-platform development accessible. This guide walks through creating a simple todo app from scratch, covering widgets, state management...', 4, 15, NOW() - INTERVAL '4 days'),
('Docker Multi-Stage Builds Explained', 'Multi-stage builds help optimise Docker images by reducing size and improving security. Here''s how to implement them effectively in your projects...', 5, 8, NOW() - INTERVAL '5 days'),
('Understanding Neural Network Backpropagation', 'Backpropagation is the backbone of neural network training. This post breaks down the mathematics and implementation details with clear examples...', 6, 20, NOW() - INTERVAL '6 days'),
('Zero Trust Security Architecture', 'Traditional perimeter-based security is obsolete. Zero Trust assumes no implicit trust and verifies every request. Here''s how to implement it...', 7, 10, NOW() - INTERVAL '7 days'),
('From Bootcamp to Senior Developer: My Journey', 'Three years ago I graduated from a coding bootcamp. Here''s how I progressed to a senior role, including mistakes I made and lessons learned...', 8, 6, NOW() - INTERVAL '8 days'),
('Building a Real-Time Chat App with WebSockets', 'Learn to build a scalable real-time chat application using WebSockets, Redis, and Node.js. Includes user authentication and message persistence...', 9, 18, NOW() - INTERVAL '9 days'),
('Contributing to Open Source: A Beginner''s Guide', 'Open source contribution seems intimidating but it''s incredibly rewarding. Start with documentation, fix typos, then gradually tackle bigger issues...', 10, 9, NOW() - INTERVAL '10 days'),
('Code Review Best Practices', 'Effective code reviews catch bugs, share knowledge, and maintain code quality. Focus on logic, not style. Be constructive, not critical...', 11, 11, NOW() - INTERVAL '11 days'),
('Solving the Two Sum Problem: Multiple Approaches', 'The classic Two Sum leetcode problem can be solved multiple ways. We''ll explore brute force, hash map, and two-pointer approaches with time complexity analysis...', 12, 13, NOW() - INTERVAL '12 days'),
('PostgreSQL Query Optimization Techniques', 'Slow queries killing your app performance? Learn about indexing strategies, query planning, and EXPLAIN ANALYZE to optimise your PostgreSQL database...', 13, 16, NOW() - INTERVAL '13 days'),
('Building a Design System from Scratch', 'Consistent UI across products requires a solid design system. This guide covers typography, colour palettes, spacing, and component libraries...', 14, 14, NOW() - INTERVAL '14 days'),
('Test-Driven Development in Practice', 'TDD feels slow initially but pays dividends in code quality and confidence. Write failing tests first, implement minimal code, then refactor...', 15, 12, NOW() - INTERVAL '15 days'),
('Microservices vs Monolith: When to Choose What', 'Microservices aren''t always the answer. Consider team size, deployment complexity, and data consistency before breaking up your monolith...', 16, 17, NOW() - INTERVAL '16 days'),
('Profiling Node.js Applications for Performance', 'Node.js performance issues often stem from blocking operations and memory leaks. Use --inspect, clinic.js, and 0x for profiling...', 17, 19, NOW() - INTERVAL '17 days'),
('Writing API Documentation That Developers Love', 'Great API docs include clear examples, error codes, and authentication details. Tools like OpenAPI and Postman collections make this easier...', 18, 8, NOW() - INTERVAL '18 days'),
('Debugging Production Issues Like a Pro', 'Production bugs are inevitable. Use structured logging, distributed tracing, and error monitoring to identify and fix issues quickly...', 19, 21, NOW() - INTERVAL '19 days'),
('Tech Industry Layoffs: What''s Really Happening?', 'Recent layoffs across major tech companies reflect economic uncertainty and over-hiring during the pandemic. Here''s how to navigate this market...', 20, 7, NOW() - INTERVAL '20 days'),
('Free Resources to Learn Web Development in 2024', 'Quality free resources for learning web development: freeCodeCamp, MDN, The Odin Project, and more. No excuses not to start learning...', 21, 9, NOW() - INTERVAL '21 days'),
('Stack Overflow Alternatives for Getting Help', 'Stack Overflow can be intimidating. Try Discord communities, Reddit programming subreddits, or GitHub discussions for more beginner-friendly help...', 22, 6, NOW() - INTERVAL '22 days'),
('Clean Code: A Handbook Review', 'Robert Martin''s Clean Code is controversial but influential. The good: naming conventions and function size. The bad: some outdated advice...', 23, 10, NOW() - INTERVAL '23 days'),
('Best Tech Conference Talks of 2023', 'Missed the conferences? Here are the must-watch talks covering React Server Components, WebAssembly, and the future of JavaScript...', 24, 11, NOW() - INTERVAL '24 days'),
('VS Code Extensions That Changed My Workflow', 'These VS Code extensions significantly improved my productivity: GitLens, Prettier, Thunder Client, and Error Lens. Here''s why...', 25, 5, NOW() - INTERVAL '25 days'),
('Freelancing as a Developer: Lessons Learned', 'Two years of freelancing taught me about client communication, project scoping, and invoicing. Here''s what I wish I knew starting out...', 26, 13, NOW() - INTERVAL '26 days'),
('Why Our Startup Failed (And What We Learned)', 'Our B2B SaaS startup failed after 18 months. Poor market research, feature creep, and insufficient funding were the main culprits...', 27, 15, NOW() - INTERVAL '27 days'),
('Remote Work: Productivity Tips That Actually Work', 'Working from home requires discipline and boundaries. Create a dedicated workspace, use time-blocking, and communicate proactively with your team...', 28, 8, NOW() - INTERVAL '28 days'),
('Leading a Development Team: First-Time Manager Tips', 'Transitioning from developer to manager is challenging. Focus on enabling your team, not micromanaging. Regular 1:1s and clear expectations help...', 29, 14, NOW() - INTERVAL '29 days'),
('Product Management for Engineers', 'Engineers often transition to product management. Understanding user needs, prioritisation frameworks, and stakeholder communication are crucial...', 30, 12, NOW() - INTERVAL '30 days'),
('Growth Hacking for Technical Products', 'Technical products require different marketing approaches. Focus on developer communities, technical content, and solving real problems...', 31, 9, NOW() - INTERVAL '31 days'),
('Building an E-commerce Platform: Architecture Decisions', 'E-commerce platforms have unique requirements: inventory management, payment processing, and high availability. Here''s our architecture...', 32, 22, NOW() - INTERVAL '32 days'),
('Indie Game Development with Unity', 'Unity makes game development accessible to solo developers. This post covers 2D game basics, sprite animation, and physics systems...', 33, 18, NOW() - INTERVAL '33 days'),
('IoT Security: Common Vulnerabilities and Fixes', 'IoT devices often have poor security. Default credentials, unencrypted communication, and lack of updates create vulnerabilities...', 34, 16, NOW() - INTERVAL '34 days'),
('Smart Contract Development Best Practices', 'Smart contracts are immutable, so security is paramount. Follow checks-effects-interactions pattern and thoroughly test edge cases...', 35, 20, NOW() - INTERVAL '35 days'),
('GraphQL vs REST: Performance Comparison', 'GraphQL reduces over-fetching but adds complexity. We compared both for our mobile app and found GraphQL reduced data transfer by 40%...', 36, 11, NOW() - INTERVAL '36 days'),
('AWS Cost Optimization: Our $10k Monthly Savings', 'AWS costs can spiral quickly. We reduced our monthly bill from $15k to $5k through reserved instances, right-sizing, and eliminating waste...', 37, 13, NOW() - INTERVAL '37 days'),
('Kubernetes Production Deployment Checklist', 'Deploying to Kubernetes in production requires careful planning. This checklist covers resource limits, health checks, and monitoring...', 38, 17, NOW() - INTERVAL '38 days'),
('Application Performance Monitoring Setup', 'APM tools like New Relic and DataDog provide crucial insights into application performance. Here''s how to set up meaningful monitoring...', 39, 10, NOW() - INTERVAL '39 days'),
('TCP vs UDP: When to Use Each Protocol', 'Understanding network protocols is crucial for distributed systems. TCP guarantees delivery but adds overhead. UDP is faster but unreliable...', 40, 12, NOW() - INTERVAL '40 days'),
('Vue 3 Composition API vs Options API', 'Vue 3''s Composition API offers better TypeScript support and code reuse. However, Options API remains simpler for basic components...', 41, 9, NOW() - INTERVAL '41 days'),
('Building Scalable Node.js Applications', 'Node.js single-threaded model requires careful design for scalability. Use clustering, caching, and async patterns effectively...', 42, 15, NOW() - INTERVAL '42 days'),
('Computer Vision with TensorFlow', 'TensorFlow makes computer vision accessible. This tutorial covers image classification, object detection, and transfer learning...', 43, 25, NOW() - INTERVAL '43 days'),
('ETL Pipeline Architecture with Apache Airflow', 'Data pipelines require orchestration and monitoring. Apache Airflow provides workflow management for complex ETL processes...', 44, 19, NOW() - INTERVAL '44 days'),
('Building Real-Time Dashboards with D3.js', 'D3.js enables powerful data visualisations. This guide covers real-time updates, responsive design, and interactive elements...', 45, 21, NOW() - INTERVAL '45 days'),
('Distributed Systems Paper: Raft Consensus Algorithm', 'The Raft consensus algorithm simplifies distributed system design. This paper review explains leader election and log replication...', 46, 30, NOW() - INTERVAL '46 days'),
('My Google Internship Experience', 'Three months at Google taught me about large-scale systems, code reviews, and engineering culture. The mentorship was invaluable...', 47, 7, NOW() - INTERVAL '47 days'),
('Lambda School Controversy: A Former Student''s Perspective', 'Lambda School promised to revolutionise education but faced criticism about job placement rates and curriculum quality. Here''s my experience...', 48, 14, NOW() - INTERVAL '48 days'),
('Why I Stopped Using Social Media as a Developer', 'Social media comparison culture affects mental health. Focusing on genuine learning and building projects is more valuable than online presence...', 49, 6, NOW() - INTERVAL '49 days'),
('Platform Update: New Features and Improvements', 'We''ve added dark mode, improved search functionality, and enhanced mobile experience. Here''s what''s new and what''s coming next...', 50, 4, NOW() - INTERVAL '50 days');
